version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Asia/Tokyo'
    assignees:
      - '6temes'
    labels:
      - 'dependencies'
      - 'ruby'
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    versioning-strategy: lockfile-only

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Asia/Tokyo'
    labels:
      - 'dependencies'
      - 'github-actions'
